name: HelloworldDemo 

# Event definition 
on: 
    pull_request:
      branches: 
        - main
    push: 
      branches:
        - "main"

permissions: 
  id-token: write 
  contents: read 

jobs:
  HelloDemoJobOne: 
      name: Outputs helloworld linux
      runs-on: ubuntu-latest 

      steps: 
        - name: Pull this repo runner 
          uses: actions/checkout@v2 

        - name: Echo Helloworld 
          run: echo "helloworld mirriad"
  HelloDemoJobTwo: 
      name: Outputs helloword on windows
      needs: HelloDemoJobOne 
      runs-on: windows-latest 
      
      steps: 
        - name: Pull repo again 
          uses: actions/checkout@v3 

        - name: Echo Helloworld on windows 
          run: echo "helloworld from windows runner"

  HelloDemoJobWindowsThree: 
      name: Outputs goodbye 
      needs: [HelloDemoJobOne, HelloDemoJobTwo]
      runs-on: ubuntu-latest 
      
      steps: 
        - name: GoodBye job  
          run: echo "GoodBye"



