name: BuildApplication

# Event behaviour 
on:
  pull_request:
    branches: 
      - "main"
  push: 
    branches: 
      - "main"
  workflow_dispatch:
    
jobs: 
  BuildApp: 
    name: Builds application 
    runs-on: ubuntu-latest 

    steps: 
      - name: Pull repo to runner 
        uses: actions/checkout@v3 
      
      - name: Install dependencies
        uses: actions/setup-java@v3
        with: 
          java-version: "17"
          distribution: temurin 
          cache: 'maven'
      
      - name: Run some test 
        run: echo "running test on app"

      - name: Lint files 
        run: echo "running lint on files"  
      
      - name: Build app with maven 
        working-directory: ./application
        run: |
          mvn --batch-mode --update-snapshots verify
          mvn -B package --file pom.xml -DskipTests

      - name: Package target jar 
        working-directory: ./application
        run: |
          mkdir app-artefacts && cp -rf target/* app-artefacts/
          tar -zcvf app-artefacts-${{ github.sha }}.tar.gz app-artefacts
          ls -ls 



        


