name: BuildApplication

# Event behaviour 
on:
  pull_request:
    branches: 
      - "main"
  push: 
    branches: 
      - "main"
  workflow_dispatch:

permissions: 
  id-token: write 
  contents: read 

jobs: 
  BuildApp: 
    name: Builds application 
    runs-on: ubuntu-latest 

    steps: 
      - name: Pull repo to runner 
        uses: actions/checkout@v3 
      
      - name: Install dependencies
        uses: actions/setup-java@v3
        with: 
          java-version: "17"
          distribution: temurin 
          cache: 'maven'
      
      - name: Run some test 
        run: echo "running test on app"

      - name: Lint files 
        run: echo "running lint on files"  
      
      - name: Build app with maven 
        working-directory: ./application
        run: |
          mvn --batch-mode --update-snapshots verify
          mvn -B package --file pom.xml -DskipTests

      - name: Package target jar 
        working-directory: ./application
        run: |
          mkdir app-artefacts && cp -rf target/* app-artefacts/
          # tar -zcvf app-artefacts-${{ github.sha }}.tar.gz app-artefacts
          # tar -zcvf app-artefacts-`git rev-parse --short HEAD`.tar.gz app-artefacts
          tar -zcvf app-artefacts-v01.tar.gz app-artefacts
          ls -ls 

      - name: Upload package 
        uses: actions/upload-artifact@v3
        with: 
          name: my-app 
          path: ./app-artefacts-v01.tar.gz

  PackageAndPush:
    name: Push application to s3
    needs: BuildApp
    runs-on: ubuntu-latest 

    steps:
      - name: Pull repo to runner 
        uses: actions/checkout@v3 
        
      - name: Upload to s3 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::658951324167:role/manual-s3-ro-oidc-role
          role-session-name: OIDCSession  

      - name: Pull shared artefacts
        uses: actions/download-artifact@v3
        with:
          name: my-app

      - name: Check file is in place 
        run: |
          ls -l 





        


